### ISSUE TITLE
Can't install ckwrap on RPi, while I can install it in desktop (Linux) without issues

### ISSUE THREAD

**Issue by wosym** [djdt/ckwrap#3]
```Collecting ckwrap==0.1.7
  Using cached https://files.pythonhosted.org/packages/09/d4/d623c3d7b7fff703a97cc25a626651aa663f11ed9aecfb4726fc60f69a80/ckwrap-0.1.7.tar.gz
    Complete output from command python setup.py egg_info:
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
    #cython: language_level=3
    #distutils: language=c++
    
    from libcpp.string cimport string
    from ckwrap cimport kmeans_1d_dp
    ^
    ------------------------------------------------------------
    
    ckwrap/_ckwrap.pyx:5:0: 'ckwrap/kmeans_1d_dp.pxd' not found
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
        cdef double [:] sizes = np.zeros(max_k, dtype=np.float64)
        cdef double [:] BIC = np.empty(max_k - min_k + 1, dtype=np.float64)
    
        cdef string cpp_method = method.encode("UTF-8")
    
        kmeans_1d_dp.kmeans_1d_dp(
                   ^
    ------------------------------------------------------------
    
    ckwrap/_ckwrap.pyx:26:16: cimported module has no attribute 'kmeans_1d_dp'
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
                &withinss[0],
                &sizes[0],
                &BIC[0],
                string(b"BIC"),
                cpp_method,
                <kmeans_1d_dp.DISSIMILARITY>criterion,
                ^
    ------------------------------------------------------------
    
    ckwrap/_ckwrap.pyx:37:13: 'DISSIMILARITY' is not a type identifier
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-arpp5fjr/ckwrap/setup.py", line 42, in <module>
        ext_modules=cythonize(ckwrap),
      File "/home/pi/antbot_release/env/lib/python3.7/site-packages/Cython/Build/Dependencies.py", line 1103, in cythonize
        cythonize_one(*args)
      File "/home/pi/antbot_release/env/lib/python3.7/site-packages/Cython/Build/Dependencies.py", line 1226, in cythonize_one
        raise CompileError(None, pyx_file)
    Cython.Compiler.Errors.CompileError: ckwrap/_ckwrap.pyx
    Compiling ckwrap/_ckwrap.pyx because it depends on /home/pi/antbot_release/env/lib/python3.7/site-packages/Cython/Includes/libcpp/string.pxd.
    [1/1] Cythonizing ckwrap/_ckwrap.pyx
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-arpp5fjr/ckwrap/
```

When checking the file it downloaded, kmeans_1d_dp.pxd is missing indeed. That explains why it doesn't know "DISSIMILARITY". 
Any idea on why this might be happening?

**Comment by wosym** [comment]
Was able to get it working by using `pip download ckwrap`, then extracting, running install on the folder, and then manually retrieving every missing file with `wget`. After downloading a bunch, it finally worked. But it was quite a hassle. I'm guessing there's something wrong with the pip package for RPi distro's?

**Comment by djdt** [comment]
Thanks for finding this. The issue was some source files (including the .pxd) were not being included, so the build would fail when a wheel wasn't available. I have updated the setup.py and manifest to include them all in the new release.
