### ISSUE TITLE
Errors installing on macOS Monterey 12.2.1

### ISSUE THREAD

**Issue by YangYiDev** [djdt/ckwrap#4]
Hello, I'm having problems with installation. The first time I tried to install I got this:

```
% pip install ckwrap    
Collecting ckwrap
  Using cached ckwrap-0.1.9.tar.gz (136 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/1g/grc48dv50bn4r7n4v86lsmv80000gn/T/pip-install-6fzqfwod/ckwrap_fd07e8d0dfe34782aed90aff3401d910/setup.py", line 1, in <module>
          from Cython.Build import cythonize
      ModuleNotFoundError: No module named 'Cython'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

_So I installed Cython, after which I tried to install again and got this:_

```
% pip install ckwrap       
Collecting ckwrap
  Using cached ckwrap-0.1.9.tar.gz (136 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [12 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/1g/grc48dv50bn4r7n4v86lsmv80000gn/T/pip-install-5pj539r0/ckwrap_0d5913ae409d4573a42a8a4dcae18e6b/setup.py", line 42, in <module>
          ext_modules=cythonize(ckwrap),
        File "/Users/yang/.pyenv/versions/3.10.2/lib/python3.10/site-packages/Cython/Build/Dependencies.py", line 970, in cythonize
          module_list, module_metadata = create_extension_list(
        File "/Users/yang/.pyenv/versions/3.10.2/lib/python3.10/site-packages/Cython/Build/Dependencies.py", line 816, in create_extension_list
          for file in nonempty(sorted(extended_iglob(filepattern)), "'%s' doesn't match any files" % filepattern):
        File "/Users/yang/.pyenv/versions/3.10.2/lib/python3.10/site-packages/Cython/Build/Dependencies.py", line 114, in nonempty
          raise ValueError(error_msg)
      ValueError: 'ckwrap/_ckwrap.pyx' doesn't match any files
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

I switched to Windows 10 and the installation worked without problems. Anyone knows what's going on? Thanks!

**Comment by tmsholy** [comment]
I just ran into the same issue on macOS Monterey 12.4 running on M1 Pro. I have also installed Cython after seeing the first error message and then got the same error.
Python 3.9.13
pip 22.1.1

**Comment by djdt** [comment]
Not sure about the Cython warning, its included in the install_requires.
I have released an updated for the missing file can you please try installing via pip again.

**Comment by tmsholy** [comment]
It works now, thank you! I'm sorry for the late response. I think this issue can be closed now. @djdt
